#sequences.py
Nucleotides=['G', 'C', 'A', 'T']
DNA_Complement={'G':'C', 'C':'G', 'A':'T', 'T':'A'} #3'-5'; reverse by using [::-1]
# doc str is when you add a 'definition' to your funciton that appears when you hover over your function
#doc str performed by using three "" pairs

DNA_Codons = {
    # 'M' - START, '_' - STOP
    "GCT": "A", "GCC": "A", "GCA": "A", "GCG": "A",
    "TGT": "C", "TGC": "C",
    "GAT": "D", "GAC": "D",
    "GAA": "E", "GAG": "E",
    "TTT": "F", "TTC": "F",
    "GGT": "G", "GGC": "G", "GGA": "G", "GGG": "G",
    "CAT": "H", "CAC": "H",
    "ATA": "I", "ATT": "I", "ATC": "I",
    "AAA": "K", "AAG": "K",
    "TTA": "L", "TTG": "L", "CTT": "L", "CTC": "L", "CTA": "L", "CTG": "L",
    "ATG": "M", # START CODON
    "AAT": "N", "AAC": "N",
    "CCT": "P", "CCC": "P", "CCA": "P", "CCG": "P",
    "CAA": "Q", "CAG": "Q",
    "CGT": "R", "CGC": "R", "CGA": "R", "CGG": "R", "AGA": "R", "AGG": "R",
    "TCT": "S", "TCC": "S", "TCA": "S", "TCG": "S", "AGT": "S", "AGC": "S",
    "ACT": "T", "ACC": "T", "ACA": "T", "ACG": "T",
    "GTT": "V", "GTC": "V", "GTA": "V", "GTG": "V",
    "TGG": "W",
    "TAT": "Y", "TAC": "Y",
    "TAA": "_", "TAG": "_", "TGA": "_" #STOP CODONS
}

# NM_000207.3 Homo sapiens insulin (INS), transcript variant 1, mRNA
NM_000207_3 = "AGCCCTCCAGGACAGGCTGCATCAGAAGAGGCCATCAAGCAGATCACTGTCCTTCTGCCATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAGCCTTTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGGGGAACGAGGCTTCTTCTACACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGTGGGGCAGGTGGAGCTGGGCGGGGGCCCTGGTGCAGGCAGCCTGCAGCCCTTGGCCCTGGAGGGGTCCCTGCAGAAGCGTGGCATTGTGGAACAATGCTGTACCAGCATCTGCTCCCTCTACCAGCTGGAGAACTACTGCAACTAGACGCAGCCCGCAGGCAGCCCCACACCCGCCGCCTCCTGCACCGAGAGAGATGGAATAAAGCCCTTGAACCAGC"
'''NM_000207.3 Homo sapiens insulin (INS), transcript variant 1, mRNA'''

# lyme Borrelia burgdorferi 23S rRNA's DNA; faulty bc contains Y bp
lyme = "ATATGGTCAAAGTAATAAGAGTCTATGGTGAATGCCTAGGAGCTTTAAGGCGAAGAAGGTCGTGGTAAGCTGCGAAAAGCTTGGGGGAGAAGCAAACATTTATTGATCCCAAGATTACCGAATGGAGTAATCCAGCTAGCAAGATGCTAGCTATCTATTATCTAAATAATAGAGGCGATACCAGGGGAAGTGAACCATCTAAGTACCCTGAGGAAAAGAAATCAAAGAGATTCCCTTAGTAGTGGCGAGCGAAAAGGGAGTAGCCCAAACTTTAAATGTGTCAAGCTGCAGAGCGTTGCATTTATGGGGTTGTAGGACGTTTAGGCTTAGTCTGTAATAAGCAAAAAAGTTACAAAATATTTATATAGAAGAATAATCTGGAAAGTTTAACCAAAGAAGGTGATAGTCCTGTAATTTAAATGTAAATATCTTTTTAAAATGTTCCTGAGTAGGACGAGGCACGAGAAACCTTGTTTGAAGCTGGGGAGACCACTCTCCAAGGCTAAATACTAGAAAGCTACCGATAGAGAAGAGTACCGTGAGGGAAAGGTGAAAAGAACCCCGGGAGGGGAGTGAAATAGAACTGAAACCGTAGACTTACAAGCAGTCAAAGCCGTAATTTATTGCGGTGATGGCGTGCCTTTTGCATAATGAACCTGCGAGTTATCATGTCTAGCAAGATTAAAGCATAGAAGTGCTGGAGTCGAAGCGAAAGCGAGTCTTAAAAGGGCGATTTAGTTAGATGTGGTAGACCCGAAGCCGAGTGATCTATTTATGGCCAGGCTGAAGCTTGGGTAAAACCAAGTGGAGGGCCGAACTCTAGTCTGTTTAAAAAGGCAGYGATGAGCTGTGAATAGGAGTGAAAGGCTAAACAAACTCGGAGATAGCTGGTTCTCCCCGAAATGGATTTAAGTTCAGCCTTATTTTAGTTTAATAGAGGTAGAGCACTAATTGAGCTAGGGCCTGTCAAAGGGTACCAAACTCAGTTAAACTCCGAATGCTATTAAATGATGAATAGGAGTGAGACTYTGGGCGATAAGGTTCATAGTCGAGAGGGAAACAACCCAGACCAACAGCTAAGGTCTCAAAAATGTGTTAAGTGGAAAAGGAGGTTTAGGTACGTAAACAGCCAGGAGGTTGGCTTAGAAGCAGCCATACCTTTAAAGAGTGCGTAATAGCTCACTGGTCGAGTACTTAAGCGCCGATAATGTAACGGGGCTAAACACATTACCGAAGCTTTGGATCTTAACGAAAGTTAAGATGGTAGGGGAGCGTTCTGTAAGCCAGAGAAGTTAAACTGGAAAGTTTGATGGAGGTATCAGAAGTGAGAATGCAGGTATGAGTAACGAAAAAATGGGTGAGATTCCCATTCGCCGAAAACCTAAGGTTTCCTGGGTAAAGGTCGTCTTCCCAGGGTTAGTCGGCCCCTAAGGCAAAGCTGAAAAGTGTAGTCGATGGGAAACGGGTTAATATTCCCGTACCTCTTATAGTTTCGATGGAGTGACGCATGAGGTTAACTACTGCTAGGCGATGGTTGTCCTAGTTTAAGCATTAAGGCGATGATCTTAATAGGAAAATCCGTTAAGAGAGCTAAGATGTGATGATGAGTGCTATTTAGGTAGCATGAAATGTAGGTAGTCAAGGTGCCAAGAAATAGCTTCTAAGGTTAGGCTATAAGGGACCGTACCGCAAACCGACACAGGTAGGTGGGATGAAAATTCTAAGGCGCGCGAGAGAATCCACGTTAAGGAACTCTGCAAAATACGTACGTAACTTCGGGATAAGTACGACCTAAGCAATTAGGTAGCATAAAAATGGTCCAAACGACTGTTTACCAAAAACACAGGTCTCTGCAAATCTGTAAAGAGAAGTATAGGGACTGACACCTGCCCGGTGCTGGAAGGTTAAGAGGAGATGTTAGTTTATACGAAGCATTGAATTTAAGCCCCAGTAAACGGCGGCCGTAACTATAACGGTCCTAAGGTAGCGAAATTCCTTGTCGGGTAAGTTCCGACCCGCACGAATGGTGTAACGATTTGGACGCTGTCTCAACGTGGAGCTCGGTGAAATTGAAGTATCGGTGAAGATGCCGATTACTTGTGGTTAGACGGAAAGACCCCGTGAACCTTTACTATAGCTTGGTATTGAGATTTGATTAAATATGTGTAGGATAGGTGGGAGACTTTGAAGCTATCTCGTTAGGGGTAGTGGAGTCAATCTTGAAATACCACCCTTGTTTAATTAGGTTTCTAACTTATAGAAATATGAGGAGAGTGCCAGGTGGGTAGTTTGACTGGGGCGGTCGCCTCCTAAAGAGTAACGGAGGTGCGCAAAGGTTACCTTAGAGTGGTTGGAAATCACTCTGTAAGTGTAAAGGCATAAGGTAGCTTAACTGTAAGACTGACAAGTCGAACAGATACGAAAGTAGGTCTTAGTGATCTGGCGGTGGCAAGTGGAAGCGCCGTCACTTAACGAATAAAAGGTACTCCGGGGATAACAGGCTTATCCTTCCCAAGAGTTCACATCGACGGAAGGGTTTGGCACCTCGATGTCGGCTCATCGCATCCTAGGGCTGGAGCAGGTCCTAAGGGTATGGCTGTTCGCCATTTAAAGCGGTACGCGAGCTGGGTTCAGAACGTCGTGAGACAGTTTGGTCCCTATCTGCCACAAGCGTTGGATATTTGAGAGGAGCTATCTTTAGTACGAGAGGACCGAGATGGACGAACCTCTAGTGTGCCAGTTATTCTGCCAAGGGTAAGTGCTGGGTAGCTACGTTCGGAAAGGATAACCGCTGAAAGCATCTAAGTGGGAAGCCTTCCTCAAGATGAGATATCCTTTAAGGGTCCTGGAAGAATACCAGGTTGATAGGTTAGAAGTGTAAGTATAGCAATATATTAAGCTGACTAATACTAATTACCCGTATCTTTGGCCATA"
'''lyme disease; Borrelia burgdorferi 23S rRNA's DNA; faulty bc contains Y bp'''

# KU178242.1 Parkinson isoform 3 (PARK2) Homo sapiens parkinson protein 2 E3 ubiquitin protein ligase isoform 3
KU178242_1 = 'ATGATAGTGTTTGTCAGGTTCAACTCCAGCCATGGTTTCCCAGTGGAGGTCGATTCTGACACCAGCATCTTCCAGCTCAAGGAGGTGGTTGCTAAGCGACAGGGGGTTCCGGCTGACCAGTTGCGTGTGATTTTCGCAGGGAAGGAGCTGAGGAATGACTGGACTGTGCAGAATTGTGACCTGGATCAGCAGAGCATTGTTCACATTGTGCAGAGACCGTGGAGAAAAGGTCAAGAAATGAATGCAACTGGAGGCGACGACCCCAGAAACGCGGCGGGAGGCTGTGAGCGGGAGCCCCAGAGCTTGACTCGGGTGGACCTCAGCAGCTCAGTCCTCCCAGGAGACTCTGTGGGGCTGGCTGTCATTCTGCACACTGACAGCAGGAAGGACTCACCACCAGCTGGAAGTCCAGGTAGATCAATCTACAACAGCTTTTATGTGTATTGCAAAGGCCCCTGTCAAAGAGTGCAGCCGGGAAAACTCAGGGTACAGTGCAGCACCTGCAGGCAGGCAACGCTCACCTTGACCCAGGGTCCATCTTGCTGGGATGATGTTTTAATTCCAAACCGGATGAGTGGTGAATGCCAATCCCCACACTGCCCTGGGACTAGTGCAGAATTTTTCTTTAAATGTGGAGCACACCCCACCTCTGACAAGGAAACATCAGTAGCTTTGCACCTGATCGCAACAAATAGTCGGAACATCACTTGCATTACGTGCACAGACGTCAGGAGCCCCGTCCTGGTTTTCCAGTGCAACTCCCGCCACGTGATTTGCTTAGACTGTTTCCACTTATACTGTGTGACAAGACTCAATGATCGGCAGTTTGTTCACGACCCTCAACTTGGCTACTCCCTGCCTTGTGTGGCTGGCTGTCCCAACTCCTTGATTAAAGAGCTCCATCACTTCAGGATTCTGGGAGAAGAGCAGTACAACCGGTACCAGCAGTATGGTGCAGAGGAGTGTGTCCTGCAGATGGGGGGCGTGTTATGCCCCCGCCCTGGCTGTGGAGCGGGGCTGCTGCCGGAGCCTGACCAGAGGAAAGTCACCTGCGAAGGGGGCAATGGCCTGGGCTGTGGGTATGGACAACGAAGAACAAAA'
'''Parkinson isoform 3 (PARK2); Homo sapiens parkinson protein 2 E3 ubiquitin protein ligase isoform 3'''